name: rails-jokes
env:
  DATABASE_URL: sqlite3:///db/development.sqlite3
build:
  steps:
    - name: Install Dependencies
      run: bundle install
deploy:
  steps:
    - name: Migrate Database
      run: bundle exec rake db:migrate
    - name: Restart App
      run: touch tmp/restart.txt
